CREATE TABLE green_user (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    username VARCHAR (20) NOT NULL,
    password VARCHAR (60) NOT NULL,
    balance BIGINT (20),
    PRIMARY KEY (id)
)DEFAULT CHARSET=UTF8;

CREATE TABLE items (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    name VARCHAR (20) NOT NULL,
    description VARCHAR (200) NOT NULL,
    photoUrl VARCHAR (200) NOT NULL,
    startingPrice BIGINT (20),
    purchasePrice BIGINT (20),
    purchasePrice INT,
    PRIMARY KEY (id)
)DEFAULT CHARSET=UTF8;

CREATE TABLE bid (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    bid BIGINT (20),
    PRIMARY KEY (id)
)DEFAULT CHARSET=UTF8;

ALTER TABLE items ADD CONSTRAINT FKm76969r4r21rywfxvyk4ouboh FOREIGN KEY (items_id) REFERENCES green_user(id);
ALTER TABLE bid ADD CONSTRAINT FKq62qs4kswcef92o9tv8d39uf1 FOREIGN KEY (bid_id) REFERENCES items(id);


